### ISSUE TITLE
Cannot import pointops

### ISSUE THREAD

**Issue by the-ponpon** [ChenYutongTHU/SplatFormer#2]
Hi,

First of all, thank you for sharing your great job.

I followed your installation steps and came out with the following issue:

Traceback (most recent call last):
  File "/root/dev/splatformer/infer.py", line 10, in <module>
    from models.feature_predictor import FeaturePredictor
  File "/root/dev/splatformer/models/feature_predictor.py", line 6, in <module>
    from .pointtransformer_v3 import PointTransformerV3Model
  File "/root/dev/splatformer/models/pointtransformer_v3.py", line 3, in <module>
    from pointcept.models.modules import PointModule
  File "/root/dev/splatformer/Pointcept/pointcept/models/__init__.py", line 6, in <module>
    from .point_transformer import *
  File "/root/dev/splatformer/Pointcept/pointcept/models/point_transformer/__init__.py", line 1, in <module>
    from .point_transformer_seg import *
  File "/root/dev/splatformer/Pointcept/pointcept/models/point_transformer/point_transformer_seg.py", line 13, in <module>
    import pointops
ModuleNotFoundError: No module named 'pointops'

Any idea why?

Thank you in advance

Pierre

**Comment by the-ponpon** [comment]
You actually need to

**Comment by qq704554563** [comment]
cd Pointcept/libs/pointops
python setup.py install
