### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/checkpoint'

### ISSUE THREAD

**Issue by HelloWorld77777777** [ChenYutongTHU/SplatFormer#8]
Excellent work！ 
But When running sh scripts/train-on-objaverse_inference.sh ，I encounted a problem that 

Traceback (most recent call last):
  File "train.py", line 401, in <module>
    app.run(main)
  File "/home/l/下载/enter/envs/splatformer/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/l/下载/enter/envs/splatformer/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train.py", line 355, in main
    model.load_state_dict(torch.load(model.resume_ckpt,map_location='cpu'))
  File "/home/l/下载/enter/envs/splatformer/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/l/下载/enter/envs/splatformer/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/l/下载/enter/envs/splatformer/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/checkpoint'

Could give some advice？

Thank you in advince

Alex

**Comment by HelloWorld77777777** [comment]
Thank you, I solved the problem!

**Comment by HelloWorld77777777** [comment]
How to generate Gaussian Splat PLY files during the evaluation process, can you give me some advice? Looking forward to your reply！
